name: Cypress tests

on: deployment_status

jobs:
  run-tests:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: cypress/base:16.13.0
      options: --user 1001

    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v2
        with:
          record: false
          command-prefix: "percy exec -- npx"
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: e2e
