name: Cypress tests

on: deployment_status

jobs:
  run-tests:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container: cypress/base:16.13.0

    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
