name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test:ci
        env:
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
      - uses: codecov/codecov-action@v3.1.6
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'renovate') }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit
